language: node_js
cache:
  directories:
    - node_modules
node_js:
    - 8.9
branches:
  only:
  - master
before_install:
    - npm install
install:
    npm install -g npm@latest
    npm --version
    npm install --registry http://registry.npmjs.org
script:
  - npm run after
  - codecov
after_success:
  - npm run coveralls